# Generated by Django 5.0.4 on 2024-04-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(help_text='The unique email address of the user.', max_length=255, unique=True, verbose_name='email')),
                ('name', models.CharField(help_text='The name of the user.', max_length=200)),
                ('referral_code', models.CharField(help_text='A unique referral code assigned to the user.', max_length=6, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.')),
                ('is_admin', models.BooleanField(default=False, help_text='Designates whether this user has admin access.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the user was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the user was last updated.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
