# Generated by Django 5.0.4 on 2024-04-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_myuser_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Points representing the number of users referred', null=True),
        ),
    ]
